# Generated by Django 3.1 on 2022-05-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(upload_to='gallery_images/'),
        ),
    ]
